interface ZIF_00_I_TRAVELTP_C
  public .


  interfaces /BOBF/IF_LIB_CONSTANTS .

  constants:
    BEGIN OF SC_ACTION,
      BEGIN OF Z00_I_TRAVELTP,
 CREATE_Z00_I_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E20157',
 DELETE_Z00_I_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E28157',
 ISSUE_MESSAGE                  TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98AF0D30D12384BA',
 LOCK_Z00_I_TRAVELTP            TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E14157',
 SAVE_Z00_I_TRAVELTP            TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E30157',
 SET_TO_CANCELLED               TYPE /BOBF/ACT_KEY VALUE '005056044E851EDB98C148C83CA26F3E',
 UNLOCK_Z00_I_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E18157',
 UPDATE_Z00_I_TRAVELTP          TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E24157',
 VALIDATE_Z00_I_TRAVELTP        TYPE /BOBF/ACT_KEY VALUE '005056044E851EEB98ADBD2A30E2C157',
      END OF Z00_I_TRAVELTP,
    END OF SC_ACTION .
  constants:
    BEGIN OF SC_ACTION_ATTRIBUTE,
        BEGIN OF Z00_I_TRAVELTP,
        BEGIN OF LOCK_Z00_I_TRAVELTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF LOCK_Z00_I_TRAVELTP,
        BEGIN OF UNLOCK_Z00_I_TRAVELTP,
 GENERIC                        TYPE STRING VALUE 'GENERIC',
 EDIT_MODE                      TYPE STRING VALUE 'EDIT_MODE',
 ALL_NONE                       TYPE STRING VALUE 'ALL_NONE',
 SCOPE                          TYPE STRING VALUE 'SCOPE',
 FORCE_INVALIDATION             TYPE STRING VALUE 'FORCE_INVALIDATION',
 LOCK_PARAMETER_BUFFER          TYPE STRING VALUE 'LOCK_PARAMETER_BUFFER',
 LEGACY_DAC_KEY                 TYPE STRING VALUE 'LEGACY_DAC_KEY',
        END OF UNLOCK_Z00_I_TRAVELTP,
      END OF Z00_I_TRAVELTP,
    END OF SC_ACTION_ATTRIBUTE .
  constants:
    BEGIN OF SC_ALTERNATIVE_KEY,
      BEGIN OF Z00_I_TRAVELTP,
 DB_KEY                         TYPE /BOBF/OBM_ALTKEY_KEY VALUE '005056044E851EEB98ADBD2A30E3E157',
      END OF Z00_I_TRAVELTP,
    END OF SC_ALTERNATIVE_KEY .
  constants:
    BEGIN OF SC_ASSOCIATION,
      BEGIN OF Z00_I_TRAVELTP,
 LOCK                           TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEB98ADBD2A30E12157',
 MESSAGE                        TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEB98ADBD2A30E0E157',
 PROPERTY                       TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEB98ADBD2A30E1E157',
      END OF Z00_I_TRAVELTP,
      BEGIN OF Z00_I_TRAVELTP_LOCK,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEB98ADBD2A30E36157',
      END OF Z00_I_TRAVELTP_LOCK,
      BEGIN OF Z00_I_TRAVELTP_MESSAGE,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEB98ADBD2A30E34157',
      END OF Z00_I_TRAVELTP_MESSAGE,
      BEGIN OF Z00_I_TRAVELTP_PROPERTY,
 TO_PARENT                      TYPE /BOBF/OBM_ASSOC_KEY VALUE '005056044E851EEB98ADBD2A30E38157',
      END OF Z00_I_TRAVELTP_PROPERTY,
    END OF SC_ASSOCIATION .
  constants:
    BEGIN OF SC_ASSOCIATION_ATTRIBUTE,
      BEGIN OF Z00_I_TRAVELTP,
        BEGIN OF PROPERTY,
 ALL_NODE_PROPERTY              TYPE STRING VALUE 'ALL_NODE_PROPERTY',
 ALL_NODE_ATTRIBUTE_PROPERTY    TYPE STRING VALUE 'ALL_NODE_ATTRIBUTE_PROPERTY',
 ALL_ASSOCIATION_PROPERTY       TYPE STRING VALUE 'ALL_ASSOCIATION_PROPERTY',
 ALL_ASSOCIATION_ATTRIBUTE_PROP TYPE STRING VALUE 'ALL_ASSOCIATION_ATTRIBUTE_PROP',
 ALL_ACTION_PROPERTY            TYPE STRING VALUE 'ALL_ACTION_PROPERTY',
 ALL_ACTION_ATTRIBUTE_PROPERTY  TYPE STRING VALUE 'ALL_ACTION_ATTRIBUTE_PROPERTY',
 ALL_QUERY_PROPERTY             TYPE STRING VALUE 'ALL_QUERY_PROPERTY',
 ALL_QUERY_ATTRIBUTE_PROPERTY   TYPE STRING VALUE 'ALL_QUERY_ATTRIBUTE_PROPERTY',
 ALL_SUBTREE_PROPERTY           TYPE STRING VALUE 'ALL_SUBTREE_PROPERTY',
        END OF PROPERTY,
      END OF Z00_I_TRAVELTP,
    END OF SC_ASSOCIATION_ATTRIBUTE .
  constants:
    SC_BO_KEY  TYPE /BOBF/OBM_BO_KEY VALUE '005056044E851EEB98ADBD2A30E04157' .
  constants:
    SC_BO_NAME TYPE /BOBF/OBM_NAME VALUE 'Z00_I_TRAVELTP' .
  constants:
    BEGIN OF SC_DETERMINATION,
      BEGIN OF Z00_I_TRAVELTP,
 ACTION_AND_FIELD_CONTROL       TYPE /BOBF/DET_KEY VALUE '005056044E851EEB98ADBD2A30E40157',
 ADMINISTRATIVE_DATA            TYPE /BOBF/DET_KEY VALUE '005056044E851EDB98C7E2EEDB81DF37',
 TRAVELAGENCY                   TYPE /BOBF/DET_KEY VALUE '005056044E851EDB98C7EBBFFEEEBF41',
 TRAVELNUMBER                   TYPE /BOBF/DET_KEY VALUE '005056044E851EDB98C7EEC244C99F42',
      END OF Z00_I_TRAVELTP,
    END OF SC_DETERMINATION .
  constants:
    BEGIN OF SC_GROUP,
 Z00_I_TRAVELTP                 TYPE /BOBF/OBM_GROUP_KEY VALUE '005056044E851EDB98C6FA98AEDCDCE8',
    END OF SC_GROUP .
  constants:
    SC_MODEL_VERSION TYPE /BOBF/CONF_VERSION VALUE '00000' .
  constants:
    BEGIN OF SC_NODE,
 Z00_I_TRAVELTP                 TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEB98ADBD2A30E08157',
 Z00_I_TRAVELTP_LOCK            TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEB98ADBD2A30E10157',
 Z00_I_TRAVELTP_MESSAGE         TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEB98ADBD2A30E0C157',
 Z00_I_TRAVELTP_PROPERTY        TYPE /BOBF/OBM_NODE_KEY VALUE '005056044E851EEB98ADBD2A30E1C157',
    END OF SC_NODE .
  constants:
    BEGIN OF SC_NODE_ATTRIBUTE,
      BEGIN OF Z00_I_TRAVELTP,
  NODE_DATA                      TYPE STRING VALUE 'NODE_DATA',
  TRAVELAGENCY                   TYPE STRING VALUE 'TRAVELAGENCY',
  TRAVELNUMBER                   TYPE STRING VALUE 'TRAVELNUMBER',
  TRAVELDESCRIPTION              TYPE STRING VALUE 'TRAVELDESCRIPTION',
  CUSTOMER                       TYPE STRING VALUE 'CUSTOMER',
  STARTDATE                      TYPE STRING VALUE 'STARTDATE',
  ENDDATE                        TYPE STRING VALUE 'ENDDATE',
  STATUS                         TYPE STRING VALUE 'STATUS',
  CHANGEDAT                      TYPE STRING VALUE 'CHANGEDAT',
  CHANGEDBY                      TYPE STRING VALUE 'CHANGEDBY',
      END OF Z00_I_TRAVELTP,
    END OF SC_NODE_ATTRIBUTE .
  constants:
    BEGIN OF SC_NODE_CATEGORY,
      BEGIN OF Z00_I_TRAVELTP,
 ROOT                           TYPE /BOBF/OBM_NODE_CAT_KEY VALUE '005056044E851EEB98ADBD2A30E0A157',
      END OF Z00_I_TRAVELTP,
    END OF SC_NODE_CATEGORY .
  constants:
    BEGIN OF SC_VALIDATION,
      BEGIN OF Z00_I_TRAVELTP,
 MANDATORY_FIELDS               TYPE /BOBF/VAL_KEY VALUE '005056044E851EDB98C6FA98AEDC7CE8',
      END OF Z00_I_TRAVELTP,
    END OF SC_VALIDATION .
endinterface.
